Add missing dependency in README
Without sphinx, the installation process as documented yield the
following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/augustin/workspace/albion/package.py", line 98, in <module>
    build_doc()
  File "albion/doc/__init__.py", line 36, in build
    exec_cmd(cmd)
  File "albion/doc/__init__.py", line 20, in exec_cmd
    stderr=PIPE, stdout=PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```